### ISSUE TITLE
¿Es valido añadir más entities o intents?

### ISSUE THREAD

**Issue by mistersoftware** [maratonadev-la/desafio-1-2020#2]
Hola,  ¿es valido dentro del desafío añadir ___intents___ y ___entities___ adicionales a los propuestos en el skill del dataset?

**Comment by OamJorge** [comment]
Hola de lo que lei, si es valido.
"No dudes en realizar los cambios que consideres necesarios siempre que el resultado sea el especificado anteriormente."

**Comment by mistersoftware** [comment]
> Hola de lo que lei, si es valido.
> "No dudes en realizar los cambios que consideres necesarios siempre que el resultado sea el especificado anteriormente."

Hola Jorge, también lo pensé en la primera lectura. Pero como también dicen que los intents y las entities ya están completos ahí entra mi duda. (tal vez solo sea permitido añadir sinónimos y ejemplos)

Gracias por tu colaboración.

**Comment by danitrod** [comment]
Hola, es valido pero no va a ayudarlo en nada. Solo vamos validar los intents y entities que pedimos en el README. Añadir otros más puede bajar la confidencia de tu asistente en detectar los que queremos.

**Comment by mistersoftware** [comment]
Tienes razón, en los intents puede ocurrir que le baje el nivel de confianza en la interpretación aunque en la practica no ocurre lo mismo con las entities. 

Muchas gracias por tu atención. Ojala mis preguntas le sirvan a alguien más. Saludos.
