### ISSUE TITLE
No puedo iniciar sesion

### ISSUE THREAD

**Issue by anp121** [maratonadev-la/desafio-1-2020#4]
Hice todos los paso, cuando entro a https://alestra-forgiving-giraffe.mybluemix.net/ y intento iniciar sesión me aparece "Error
La contraseña ingresada no es válida. Si has olvidado tu contraseña, elimina tu aplicación en la lista de recursos de IBM Cloud y vuelva a realizar el despliegue." Lo intente a hacer de nuevo, y la única contraseña que elegí me da error.

**Comment by danitrod** [comment]
@anp121 creo que has llenado incorrectamente el formulario para despliegue de la aplicación. Quita tu app en la lista de recursos de IBM Cloud y intentalo de nuevo por favor

**Comment by danitrod** [comment]
si tienes mas dudas nos llame en nuestro discord https://discord.gg/JAHqHxz
