### ISSUE TITLE
Consulta antes de continuar

### ISSUE THREAD

**Issue by RLuisalmada** [maratonadev-la/desafio-1-2020#5]
Buenos días. Lo mío es únicamente un par de dudas (es la primera vez que trabajo con esta tecnología, en realidad soy programador COBOL).

Seguí los pasos del instructivo (video) para poder hacer el reto, y me surgen las siguientes dudas:
1.-El paso 5 (Envío), es para realizar una vez que hicimos las modificaciones que queríamos hacer o está bien que haya seguido el video y hecho ese paso? (estaba compenetrado con el video y seguí de largo)

2.-En el video, cuando están haciendo ese paso, no cambian la url del repositorio. En mi caso era la misma de la cual descargué el código (https://github.com/maratonadev-la/desafio-1-2020)... es correcto que haya dejado eso? Mi duda surge debido a que me aparece un cuadro titulado "Build" con el nombre de "Libardo Lara", y otro titulado "Deploy", con mi nombre. Entonces, antes de continuar o editar algo que no deba, quería asegurarme de no haberme equivocado.

 Desde ya, muchas gracias.

**Comment by danitrod** [comment]
Hola @RLuisalmada, bien venido a la Maratón. Sobre la primera pregunta, no hay problema hacer el despliegue de la aplicación antes de modificar el asistente. Cualquier alteración en el asistente automaticamente impactará en la llamada API para el servicio. Sobre la segunda, no necesitas cambiar nada en la parte de GitHub del formulario, solo autorizar el uso del app, lo que necesitas cambiar es en la parte de Delivery Pipeline.
Espero haberte ayudado.

**Comment by danitrod** [comment]
si tienes mas dudas nos llame en nuestro discord https://discord.gg/JAHqHxz
