### ISSUE TITLE
Incertidumbre sobre la tecnología

### ISSUE THREAD

**Issue by samrojo** [maratonadev-la/desafio-1-2020#6]
Saludos,

Comento de entrada es mi primera vez trabajando con tecnología de IBM y el asistente de Watson. Debido a que continuamente fallé en la segunda etapa del deploy eliminé todo y volví a crear la herramienta pero deje que el nombre se generase por default.

El error que obtengo es:  FAILED
Incorrect Usage. Requires old app name and new app name as arguments.

Sin embargo, el url de mi antiguo deploy sigue funcionando, la etapa del build del nuevo modelo se sigue generando exitosamente pero para ser sincero me temo que estoy bastante perdido.

**Comment by samrojo** [comment]
Revisando el log del deploy exitoso, se realizó con el nombre actual del asistente, por lo tanto tengo menos idea de lo que pueda causar este error. ¿Será prudente volver a exportar mi json, borrar todo y volver a generar todo?

**Comment by danitrod** [comment]
Hola @samrojo, si la url de tu antiguo deploy segue funcionando, no hay problema ninguno, puedes seguir usando el app antiguo. No necesitas borrar nada, puedes cambiar las credenciales del asistente hacendo clic en el botón arriba de la página. ¿Que error obtenia en la segunda etapa del deploy?

**Comment by danitrod** [comment]
si tienes mas dudas nos llame en nuestro discord https://discord.gg/JAHqHxz

**Comment by samrojo** [comment]
Muchas gracias!

Efectivamente en el deploy original todo seguia funcionando y se actualizaba acorde a los avances en los skills. El error de haber intentanto hacer otros deploys eran:

FAILED
Incorrect Usage. Requires old app name and new app name as arguments

NAME:
   rename - Rename an app

USAGE:
   cf rename APP_NAME NEW_APP_NAME

Showing health and status for app Watson in org MyOrgName / space Space_name as my@mail.com...

App 'Watson' not found.
FAILED

Sin embargo puedo seguir enviando intentos sin problema en el url original. Muchas gracias por la ayuda, un saludo.
