### ISSUE TITLE
Consulta dialogs

### ISSUE THREAD

**Issue by chamakov** [maratonadev-la/desafio-1-2020#7]
Estoy realizando la implementación de los dialogs de watson, sin embargo tengo un escenario raro, al momento de agregar un nuevo nodo hijo, a un nodo principal y realizar los flujos, una variable previamente seteada desaparece, generando que de esta manera se tengan que volver a llenar los slots ¿Alguien podría apoyarme con este tema?

**Comment by danitrod** [comment]
@chamakov recomiendo que entre en nuestro server Discord https://discord.gg/JAHqHxz

envie la duda allá y la contestamos mejor
